version: "3.9"
services:
  mongodb:
    container_name: mongo
    command: mongod --quiet
    image: mongo:latest
    ports:
      - 27017:27017
    logging:
      driver: "none"
    volumes:
      - mongodb_data_container:/data/db
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - 5000:5000
    stdin_open: true
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    restart: always
    depends_on:
      - backend
volumes:
  mongodb_data_container:
