version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    #   - /backend/node_modules
    ports:
      - 5000:5000
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    restart: always
    depends_on:
      - backend

    # version: "3.9"
# services:
#   backend:
#     container_name: backend
#     restart: always
#     build: backend
#     volumes:
#       - ./backend:/usr/src/app
#       - /usr/src/app/node_modules
#     expose:
#       - 5000

# backend:
#   container_name: backend
#   build: ./backend
#   ports:
#     - "5000:5000"
#   restart: always
#   env_file:
#     - ./backend/.env
#   volumes:
#     - ./backend:/usr/src/app
#     - /usr/src/app/node_modules
# volumes:
# - ./backend:/usr/app/backend
# - /usr/app/backend/node_modules
# volumes:
#   node_modules:
# app:
#   container_name: app
#   build: ./app
#   ports:
#     - "3000:3000"
#   restart: always
#   volumes:
#     - ./app/node_modules
#     - ./app:/usr/src/app
# admin:
#   container_name: admin
#   build: ./admin
#   ports:
#     - "3001:3001"
#   restart: always
#   volumes:
#     - ./admin/node_modules
#     - ./admin:/usr/src/admin
# landing:
#   build: ./landing
#   ports:
#     - "3002:3002"
#   stdin_open: true
#   volumes:
#     - ./landing/usr/app/node_modules
#     - ./landing:/usr/app
#   depends_on:
#     - admin

